name: mascotas_app_nueva
description: "Aplicación para gestión de mascotas con Firebase"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2

  line_icons: ^2.0.1

  image_picker: ^1.0.4
  firebase_storage: 12.4.5
  cached_network_image: ^3.3.0

  # Paquetes básicos
  cupertino_icons: ^1.0.8

  # Firebase Core
  firebase_core: ^3.13.0

  # Autenticación
  firebase_auth: ^5.0.0
  google_sign_in: ^6.1.0  # Para autenticación con Google

  # Base de datos
  cloud_firestore: ^5.6.7

  # Futuras implementaciones (ya las tenemos en vista)
  fluttertoast: ^8.2.2  # Para notificaciones toast
  provider: ^6.0.5     # Para gestión de estado

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Configuración de assets
  assets:
    - assets/images/google_logo.png
    - assets/images/app_logo.png  
    - assets/images/pet_background.jpg
    
  # Opcional: Fuentes personalizadas (si las necesitaras)
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700