name: mascotas_app_nueva
description: "Aplicación para gestión de mascotas con Firebase"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependencias principales
  intl: ^0.20.2
  line_icons: ^2.0.1
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5  # Añadido para storage
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.1.0

  # Manejo de imágenes
  image_picker_web: ^4.0.0  # Para web
  cached_network_image: ^3.3.0  # Para mostrar imágenes desde URLs
  image: ^4.0.17  # Para procesamiento de imágenes

  # Utilidades
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  uuid: ^4.5.1  # Para generar IDs únicos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/google_logo.png
    - assets/images/app_logo.png  
    - assets/images/pet_background.jpg
    - assets/images/default_pet.png  # Añadido
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700